name = "icc-orm-engine"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[services]]
binding = "mission-comms"
service = "icc-mission-communications"

[[durable_objects.bindings]]
name = "ORM_STATE"
class_name = "ORM_STATE"

